### ISSUE TITLE
能开个分支改成跟geoip可以通过变量获取值么？

### ISSUE THREAD

**Issue by xianhuawei** [youzan/ngx_http_html_sanitize_module#7]
有个需求是通过ipip获取ip对应的位置信息记录到日志 以便后续分析

类似 http://nginx.org/en/docs/http/ngx_http_geoip_module.html 中的

$geoip_area_code
telephone area code (US only).
This variable may contain outdated information since the corresponding database field is deprecated.
$geoip_city_continent_code
two-letter continent code, for example, “EU”, “NA”.
$geoip_city_country_code
two-letter country code, for example, “RU”, “US”.
$geoip_city_country_code3
three-letter country code, for example, “RUS”, “USA”.
$geoip_city_country_name
country name, for example, “Russian Federation”, “United States”.

能否开新的分支把解析出来的：
"中国", // 国家
"天津", // 省会或直辖市（国内）
"天津", // 地区或城市 （国内）
"", // 学校或单位 （国内）
"鹏博士", // 运营商字段（只有购买了带有运营商版本的数据库才会有）
"39.128399", // 纬度 （每日版本提供）
"117.185112", // 经度 （每日版本提供）
"Asia/Shanghai", // 时区一, 可能不存在 （每日版本提供）
"UTC+8", // 时区二, 可能不存在 （每日版本提供）
"120000", // 中国行政区划代码 （每日版本提供）
"86", // 国际电话代码 （每日版本提供）
"CN", // 国家二位代码 （每日版本提供）
"AP" // 世界大洲代码 （每日版本提供）

这几个变成类似上面的可以记录到access_log的变量呢？
谢谢啦

**Comment by detailyang** [comment]
Hello. 

@xianhuawei  

这个需求本来应该在调用端做的，当然在 nginx 这侧也不是不可以。之所以不暴露的这些变量的原因是由于 datx 文件的数据结构决定了，它的内部实现是按照顺序的方式存储，在转换它的数据到 JSON 时，我们采取了一种技巧，并不在乎它内部的顺序，而是按照既定的顺序一一转换为 JSON 数组，优点在于以后 datx 新增一个字段，并不需要修改任何代码。

你的需求我建议你直接使用 [openresty](http://openresty.org/en/) 实现，或者编译 [lua-nginx-module](https://github.com/openresty/lua-nginx-module) 到 nginx，我提供一种取巧的方法，仅供参考。

```nginx

    log_format ipip '$ipip_country| $ipip_province| $ipip_city| $ipip_org| $ipip_service| $ipip_latitude| $ipip_longitude| $ipip_timezone| $ipip_code| $ipip_country_phone| $ipip_contry| $ipip_world_code';

    server {
	listen 7777;

	set $ipip_country "";
	set $ipip_province "";
	set $ipip_city "";
	set $ipip_org "";
	set $ipip_service "";
	set $ipip_latitude "";
	set $ipip_longitude "";
	set $ipip_timezone "";
	set $ipip_code "";
	set $ipip_country_phone "";
	set $ipip_contry "";
	set $ipip_world_code "";

	location = /ipip {
               	access_log  logs/access.log  ipip;
		content_by_lua_block {
			local cjson
			local cjson_safe = require "cjson.safe"
			local cjson_decode = cjson_safe.decode
			local args = ngx.req.get_uri_args()
			local res =  ngx.location.capture('/_ipip', args)
			local ipip = cjson_decode(res.body)
			if ipip == nil then
				return ngx.exit(500)
			end

			ngx.var.ipip_country = ipip.data[1]
			ngx.var.ipip_province = ipip.data[2]
			ngx.var.ipip_city = ipip.data[3]
			ngx.var.ipip_org = ipip.data[4]
			ngx.var.ipip_service = ipip.data[5]
			ngx.var.ipip_latitude = ipip.data[6]
			ngx.var.ipip_longitude = ipip.data[7]
			ngx.var.ipip_timezone = ipip.data[8]
			ngx.var.ipip_code = ipip.data[9]
			ngx.var.ipip_country_phone = ipip.data[10]
			ngx.var.ipip_contry = ipip.data[11]
			ngx.var.ipip_world_code = ipip.data[12]

			ngx.say(res.body)
		}
	}

	location = /_ipip {
                internal on;
                ipip on;
	}
    }
```

**Comment by detailyang** [comment]
顺便一提，麻烦在 [https://github.com/youzan/ngx_http_ipip_module](https://github.com/youzan/ngx_http_ipip_module) 下提交 issue，本仓库只维护跟 html sanitize 相关的问题。
